### ISSUE TITLE
"stg pop" on conflicting push breaks further stg commands

### ISSUE THREAD

**Issue by dhowells** [stacked-git/stgit#276] opened 2023-02-15 11:18 UTC
I popped all the patches on a branch, used "stg rebase" and did "stg push" which resulted in a conflict:

   warthog>stg push
   > iocb-write (conflict)
   error: Merge conflicts. Resolve conflicts manually then refresh or undo the operation with `stg undo --hard`.
   UU fs/splice.c

I then accidentally did "stg pop" rather than "stg undo --hard":

   warthog3>stg pop
   error: The reference "refs/patches/iov-extract-2/iocb-write" should have content 
   575b0952abb1ea09f34fef9840263f44d0d8e45d, actual content was 
   d5b3e74bd4c76f7c05fcd161ca430667fe48bee3

and now further commands, such as "stg repair", "stg undo --hard" and "stg series" all fail with a repeat of that error.

**Comment by dhowells** [comment] 2023-02-15 11:48
I managed to fix the broken repo with:
   git update-ref refs/patches/iov-extract-2/iocb-write \
   575b0952abb1ea09f34fef9840263f44d0d8e45d

**Comment by jpgrayson** [comment] 2023-02-16 23:40
I appreciate this issue report, @dhowells.

I've made some attempt to reproduce the behavior, but without success. I tried HEAD, v2.1.0, and v2.0.4.

Are you able to reproduce this issue? Or was this a one-off occurrence for you?

If there is any more context you could provide? I'd like to know the StGit and git versions as well anything that might have made your stack interesting.

One last note: there is a test in the test suite that attempts to cover this case. See `t/t1203-push-conflict.sh` where there is a test "Check that pop will fail while there are unmerged conflicts".

**Comment by dhowells** [comment] 2023-02-17 07:58
commit 4245bdb591adbf1caf82434cb808b4b8648fe217 is the head of the stgit tree I built from.

**Comment by dhowells** [comment] 2023-02-17 08:36
I can't seem to reproduce it either. stg pop complains that outstanding conflicts need resolving or that the index is dirty.

**Comment by jpgrayson** [comment] 2023-07-04 21:15
Closing since we have not ever been able to reproduce this issue.

**Closed by jpgrayson** 2023-07-04 21:15 UTC

**Comment by jrajahalme** [comment] 2023-11-28 14:46
Just happened for me right after `stg rebase`. `git update-ref` does not help as it keeps ping-ponging between two commits with the same error. I would appreciate help in forcibly removing stgit metadata manually.
