### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by cvoltz** [stacked-git/stgit#61] opened 2020-05-07 00:45 UTC
After refreshing a patch, stgit generates this error when running `stg series -d`:
```
Error: Unhandled exception:
Traceback (most recent call last):
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/main.py", line 195, in _main
    ret = command.func(parser, options, args)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/commands/delete.py", line 102, in func
    allow_conflicts=allow_conflicts)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/transaction.py", line 132, in __init__
    self._assert_head_top_equal()
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/transaction.py", line 200, in _assert_head_top_equal
    if not self.stack.head_top_equal():
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/stack.py", line 296, in head_top_equal
    top = self.patches.get(self.patchorder.applied[-1]).commit
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/stack.py", line 235, in get
    return self._patches[name]
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/objcache.py", line 21, in __getitem__
    self.__objects[name] = self.__create(name)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/stack.py", line 222, in create_patch
    p.commit  # raise exception if the patch doesn't exist
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/stack.py", line 42, in commit
    return self._stack.repository.refs.get(self._ref)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/git/repository.py", line 79, in get
    return self._repository.get_commit(self._refs[ref])
KeyError: u'refs/patches/build-time/refresh-temp'
```

`stg series` works without generating an error (refresh-temp is at the top of the stack). Unfortunately, most `stg` commands now fail with either a `KeyError` or an `AssertionError`.

`stg repair`:
```
Error: Unhandled exception:
Traceback (most recent call last):
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/main.py", line 195, in _main
    ret = command.func(parser, options, args)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/commands/repair.py", line 94, in func
    patches = [stack.patches.get(pn) for pn in patchorder.all]
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/stack.py", line 235, in get
    return self._patches[name]
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/objcache.py", line 21, in __getitem__
    self.__objects[name] = self.__create(name)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/stack.py", line 222, in create_patch
    p.commit  # raise exception if the patch doesn't exist
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/stack.py", line 42, in commit
    return self._stack.repository.refs.get(self._ref)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/git/repository.py", line 79, in get
    return self._repository.get_commit(self._refs[ref])
KeyError: u'refs/patches/build-time/refresh-temp'
```

`stg pop` and `stg delete refresh-temp` generate the same exception (just a little different backtraces).

`stg undo` and `stg reset` (with various older states):
```
Error: Unhandled exception:
Traceback (most recent call last):
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/main.py", line 195, in _main
    ret = command.func(parser, options, args)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/commands/undo.py", line 71, in func
    return trans.run(stack.repository.default_iw, allow_bad_head=True)
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/transaction.py", line 257, in run
    self._check_consistency()
  File "/home/cvoltz/.local/lib/python2.7/site-packages/stgit/lib/transaction.py", line 244, in _check_consistency
    assert self.stack.patches.exists(pn)
AssertionError
```

The documentation doesn't indicate how one is supposed to recover from a situation like this. What needs to be done to get things working again?

## Debug info

stgit version: 0.22
OS: CentOS 7.8

```
$ stg log | head -5
996a175   Wed, 6 May 2020 18:27:10 -0500   refresh (create temporary patch)
98538bd   Wed, 6 May 2020 18:26:54 -0500   refresh
91973e3   Wed, 6 May 2020 18:26:54 -0500   refresh (create temporary patch)
98b29c0   Wed, 6 May 2020 14:37:20 -0500   pop
131fe96   Wed, 6 May 2020 14:36:52 -0500   goto
stg log: git failed with code -13
```

**Comment by jpgrayson** [comment] 2020-05-07 03:43
Hi @cvoltz. I'm really sorry that these problems are happening to you.

I am only able to give this issue a few minutes this evening. Here are some scattered thoughts and ideas:

- Python 2. It's deprecated. This issue _smells_ like a unicode vs str issue, which I've seen many of in various forms as I ported StGit to run on Python 3.

- It _might_ be possible that your current stack could be recovered by running StGit with Python 3. Depends on whether whatever problem exists in the StGit metadata trips-up Python 3 in the same way. Worth a try. This would be the easiest path to recovery if it works.

- I wonder if you could offer some additional details about your stack that might help reveal what triggered this bug? For example, were any non-ascii characters present in any of:
  - Author name/email
  - Commit message
  - Patch name
  - The blobs (files) in the patch
- Also, what locale/LANG are in use in your environment. `echo $LANG`. Is it something other than `en_US.UTF-8`?
- And were there any other special characters in the patch names? E.g. `/` is known to cause trouble.

As for other potential paths to recover, the data is all there in your git repo, but StGit's metadata seems to be in an inconsistent state. It might be helpful to do a deeper inspection of the StGit metadata. This is extra fun because StGit still has two parallel mechanisms for the same metadata (one of which will be going away soon).

Old metadata is in `.git/patches/$BRANCH/`

New metadata exists as objects in the repo in the `$BRANCH.stgit` branch, e.g. `build-time.stgit` in your case. This metadata can be accessed with `git show`:

- `git show build-time.stgit:meta`
- `git show build-time.stgit:patches/$PATCH_NAME`

In the patch-specific metadata, there are git hashes labeled "bottom" and "top". The patch's diff can be recovered with:

`git diff $BOTTOM $TOP`

You could potentially use the above to manually export your stack's patches as patch files which could then be imported with `stg import` into a new/clean branch. Tedious, yes, but it is a path to getting your patch data back.

I guess that was more than a few minutes :smile:. Anyway, good luck and sorry again for the trouble. And any details would be great, would love to reproduce this issue.

**Comment by cvoltz** [comment] 2020-05-07 16:06
Thanks for the quick reply.

CentOS 7 does offer Python 3 support, it just doesn't use it by default:
```
$ python --version
Python 2.7.5

$ python2 --version
Python 2.7.5
                                                                                                
$ python3 --version
Python 3.6.8
```

Since you prefer Python 3 to be used, I would suggest that the `Makefile` be updated to check and see if `python3` is available but not the same as `python` and use `python3` instead.

I didn't see any documentation on how to build the project with Python 3 support but after I looked at the `Makefile`, it looked like this would build and install it with Python 3:
```
PYTHON=python3 make clean all doc install{,-doc,-html}
```
It definitely used Python 3 during the build and it looks like it is using it for `stg`:
```
$ head -5 ~/.local/bin/stg
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# -*- python-mode -*-
from __future__ import (
    absolute_import,
```
Unfortunately, I still get the KeyError and AssertionError as before:
```
Error: Unhandled exception:
Traceback (most recent call last):
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/main.py", line 195, in _main
    ret = command.func(parser, options, args)
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/commands/series.py", line 300, in func
    config.get("stgit.color.current"),
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/commands/series.py", line 193, in __print_patch
    output = prefix + patch_str + ' # ' + __get_description(stack, patch)
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/commands/series.py", line 137, in __get_description
    cd = stack.patches.get(patch).commit.data
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/lib/stack.py", line 235, in get
    return self._patches[name]
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/lib/objcache.py", line 21, in __getitem__
    self.__objects[name] = self.__create(name)
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/lib/stack.py", line 222, in create_patch
    p.commit  # raise exception if the patch doesn't exist
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/lib/stack.py", line 42, in commit
    return self._stack.repository.refs.get(self._ref)
  File "/home/cvoltz/.local/lib/python3.6/site-packages/stgit/lib/git/repository.py", line 79, in get
    return self._repository.get_commit(self._refs[ref])
KeyError: 'refs/patches/build-time/refresh-temp'
```
I did find this interesting:
```
$ stg series | tail -6
+ todo
> refresh-temp
- wip
- jfile
- notes
- cache

$ stg show refresh-temp
stg show: refresh-temp: Unknown patch or revision name
```

Author name and email, commit messages, and patch names are ASCII only characters (lower 127). Patch names use only lowercase characters, numbers, a period, and a dash. The blobs in the patch do have these Unicode characters: ✓ • ✘ and there a few binary files (`.tar.gz`).

My environment has: `LANG=en_US.UTF-8`

I did try and come up with a setup of steps to reproduce the problem on a clean repo which I could provide to you but I wasn't successful. I'll try again with Unicode characters in the blob and I'll keep the broken branch around for a few days in case you have anything else you want me to look at.

I was able to run `stg export` to get the patches up through the `todo` patch (the series file showed up to `refresh-temp` but the file was not created). I was able to use `stg show` to get the patches after `refresh-temp`. Since I still had my editor open at the time the problem occurred, I was able to save the file again and run a diff to reconstruct the `refresh-temp` patch. So, I was able to recover all the patches. I updated the `series` file to include all of the patches and was able to import them up to `wip` which failed to apply. `wip` and `refresh-temp` appear to be the same patch (so maybe that gives a clue on where the `stg refresh` command was in the process when it failed). I was able to import the remaining patches individually, and after a few commands, get the stack back to the same set of applied and unapplied. It would be nice if there was a way to export and import both the applied and unapplied patches.

Thanks for your help.

**Comment by cvoltz** [comment] 2020-05-15 19:26
The corruption occurred again during a refresh of an existing patch that was at the top of the stack. I'm going to revert to an older version of stg in hopes of not running into the corruption again. The version in EPEL is 0.17.1 which is pretty old. That is what I was using before I upgraded to 0.22. Do you have any recommendation for a version which you think might be more stable?

**Comment by jpgrayson** [comment] 2020-05-15 20:36
Hi @cvoltz. I am sorry this issue happened again. And thank you for all the detail you previously provided.

The backtraces from after the `refresh` failure indicate that the specific metadata inconsistency is that the 'refresh-temp' patch was partially created such that it is present in `.git/patches/$BRANCH/applied`, but does not apparently does not have a corresponding entry at `.git/refs/patches/$BRANCH/refresh-temp`. It is hard to tell what went wrong at `refresh` time, however, since all the backtraces are from commands run afterwards.

A contributing factor to this issue is, as I mentioned previously, that StGit currently has two parallel sources of metadata. While this is not the cause for whatever happened at `refresh` time, it is relevant for why the stack ended up in an inconsistent state.

For the past year+, I have been chipping away at the code getting everything converted to the new metadata. That work is nearly done and will be in an upcoming StGit 1.0 release. Prior to 1.0, a 0.23 release is coming in the near future, but 0.23 does not have any changes that will affect the problem at hand.

Regarding older releases, I don't know when this issue emerged. The split metadata problem has existed for at least a decade, so cannot reasonably go back to a version before that problem existed. The 0.19 release introduced Python3 support--good chance I caused this breakage in that release, so perhaps 0.18? Note that the stack metadata format changed in 0.20, so you would have to re-create your stacks with the older version of StGit if you downgrade to a version <0.20.

**Comment by jpgrayson** [comment] 2021-09-20 20:45
I'm closing this issue because there is no sightings of this problem in StGit >= 1.0.

Also, some other things mentioned in this thread have been resolved:

- StGit now uses `#!/usr/bin/env python3` shebangs.
- Installing development versions of StGit with `pip` now works well. If StGit is installed with `pip`, then it can also be cleanly uninstalled with `pip`.

**Closed by jpgrayson** 2021-09-20 20:45 UTC

**Comment by cvoltz** [comment] 2022-02-09 22:37
I'm pretty sure this problem occurred due to an unintentional mixing of versions of stgit between my laptop and workstation. I've made sure they both have the same version now.
